version: '3.7'
services:
  error_map_reduce:
    build:
      context: ./error_map_reduce
      dockerfile: Dockerfile
    image: error_map_reduce:v1
    user: root
    restart: always
    deploy:
      replicas: 1
    volumes:
      - error_output:/output
  map_reduce:
    build:
      context: ./map_reduce
      dockerfile: Dockerfile
    image: map_reduce:v1
    user: root
    restart: always
    deploy:
      replicas: 1
    volumes:
      - output:/output
  general_reduce:
    build:
      context: ./general_reduce
      dockerfile: Dockerfile
    image: general_reducer:v1
    user: root
    restart: always
    depends_on:
      - error_map_reduce
      - map_reduce
    deploy:
      replicas: 1
    volumes_from:
      - error_map_reduce
      - map_reduce