build:
	cd ./error_map_reduce/mapper && ${MAKE} build && cd ..
	cd ./error_map_reduce/reducer && ${MAKE} build && cd ..
	cd ./h_map_reduce/mapper && ${MAKE} build && cd ..
	cd ./h_map_reduce/reducer && ${MAKE} build && cd ..

clean:
	cd ./error_map_reduce/mapper && ${MAKE} clean && cd ..
	cd ./error_map_reduce/reducer && ${MAKE} clean && cd ..
	cd ./h_map_reduce/mapper && ${MAKE} clean && cd ..
	cd ./h_map_reduce/reducer && ${MAKE} clean && cd ..
	rm -rf ./bin
